[program:queue-default]
command=php /var/www/html/artisan queue:work redis --queue=default,reports --tries=3 --backoff=30 --max-time=3600
numprocs=4
autostart=true
autorestart=true
stopwaitsecs=360
user=www-data

[program:queue-long]
command=php /var/www/html/artisan queue:work redis-long --queue=long --tries=1 --timeout=960 --max-time=7200
numprocs=1
autostart=true
autorestart=true
stopwaitsecs=1000
user=www-data
